# --- Serving options --- #

url: "https://sultonov.github.io"
baseurl: ""

title: "Welcome to"
description: "Programmer from Uzbekistan"
avatar: "/img/44565548_1926078517485074_8854205888227966976_o.jpg"

timezone: "Asia/Tashkent"
markdown: kramdown
highlighter: rouge
paginate: 5
paginate_path: "/blog/page:num/"
excerpt_separator: <!--more-->

disqus: "sultonov"

google_analytics: "UA-134202028-1"

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      show-share: true # add sharing buttons to all blog posts
      show-subscribe: true # add subscribe email to all blog posts
  -
    scope:
      path: "" # all files
    values:
      layout: "page"
      show-avatar: true

author:
  name: Yura Sultonov
  email: "sultonovyura@gmail.com"
  facebook: yura.sultonov
  github: sultonov
  twitter: yura_sultonov
  linkedin: yura-sultonov